In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mumbai-rent-data-bagic-bricks/mumbai_data.csv

In [5]:
df = pd.read_csv(r'/kaggle/input/mumbai-rent-data-bagic-bricks/mumbai_data.csv')
df.head()

,title,price,Furnishing,Tenant Preferred,Car Parking,Availability,Carpet Area,Floor,facing,Society,Bathroom,Balcony,overlooking,Ownership,Super Area,Dimensions,Owner Resides
0,"3 BHK Flat for Rent in Lodha World One, Worli...",₹3.5 Lac,Semi-Furnished,Bachelors/Family,2 Covered,Immediately,2198 sqft,37 out of 75,West,Lodha World One,3.0,3,NaN,NaN,NaN,NaN,NaN
1,"1 BHK Flat for Rent in Piramal Revanta, Mulun...","₹41,000",Semi-Furnished,Family,1 Covered,Immediately,474 sqft,18 out of 48,East,Piramal Revanta,2.0,NaN,"Pool, Garden/Park, Main Road",NaN,NaN,NaN,NaN
2,"3 BHK Flat for Rent in Lodha World View, Worl...",₹3.9 Lac,Semi-Furnished,Family,2 Covered,Immediately,1700 sqft,15 out of 79,East,Lodha World View,4.0,1,Garden/Park,NaN,NaN,NaN,NaN
3,"4 BHK Flat for Rent in Lodha Kiara, Worli, Mu...",₹3 Lac,Semi-Furnished,Bachelors/Family,3 Covered,Immediately,1676 sqft,39 out of 72,North,Lodha Kiara,4.0,NaN,Garden/Park,NaN,NaN,NaN,NaN
4,"3 BHK Flat for Rent in Bhakti Park, Wadala Ea...","₹80,000",Unfurnished,Bachelors/Family,1 Covered,Immediately,927 sqft,13 out of 18,West,Bhakti Park,3.0,NaN,"Garden/Park, Pool, Main Road",NaN,NaN,NaN,NaN

In [6]:
df.isnull().sum()

title                  0
price                  0
Furnishing             3
Tenant Preferred       0
Car Parking          820
Availability           0
Carpet Area          251
Floor                 78
facing               393
Society              606
Bathroom               3
Balcony              822
overlooking          428
Ownership           1299
Super Area          1249
Dimensions          1496
Owner Resides       1468
dtype: int64

In [7]:
df.shape

(1500, 17)

In [8]:
missing_columns = df.columns[df.isnull().any()]  # Identify columns with missing values
print("Columns with missing values:")
print(missing_columns)

# Option 1: Drop rows or columns with missing values
# df.dropna(inplace=True)  # Uncomment this line to drop rows with missing values
# df.dropna(axis=1, inplace=True)  # Uncomment this line to drop columns with missing values

# Option 2: Fill missing values with appropriate values
# Example: Fill missing values in numeric columns with the mean
numeric_columns = df.select_dtypes(include=[np.number]).columns
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())

# Example: Fill missing values in categorical columns with the mode
categorical_columns = df.select_dtypes(include=[np.object_]).columns
df[categorical_columns] = df[categorical_columns].fillna(df[categorical_columns].mode().iloc[0])

Columns with missing values:
Index(['Furnishing', 'Car Parking', 'Carpet Area', 'Floor', 'facing',
       'Society', 'Bathroom', 'Balcony', 'overlooking', 'Ownership',
       'Super Area', 'Dimensions', 'Owner Resides'],
      dtype='object')

In [9]:
df.isnull().sum()

title               0
price               0
Furnishing          0
Tenant Preferred    0
Car Parking         0
Availability        0
Carpet Area         0
Floor               0
facing              0
Society             0
Bathroom            0
Balcony             0
overlooking         0
Ownership           0
Super Area          0
Dimensions          0
Owner Resides       0
dtype: int64

In [10]:
df.head()

,title,price,Furnishing,Tenant Preferred,Car Parking,Availability,Carpet Area,Floor,facing,Society,Bathroom,Balcony,overlooking,Ownership,Super Area,Dimensions,Owner Resides
0,"3 BHK Flat for Rent in Lodha World One, Worli...",₹3.5 Lac,Semi-Furnished,Bachelors/Family,2 Covered,Immediately,2198 sqft,37 out of 75,West,Lodha World One,3.0,3,Main Road,Freehold,600 sqft,100 X 70 ft Sqft,Same Premise
1,"1 BHK Flat for Rent in Piramal Revanta, Mulun...","₹41,000",Semi-Furnished,Family,1 Covered,Immediately,474 sqft,18 out of 48,East,Piramal Revanta,2.0,1,"Pool, Garden/Park, Main Road",Freehold,600 sqft,100 X 70 ft Sqft,Same Premise
2,"3 BHK Flat for Rent in Lodha World View, Worl...",₹3.9 Lac,Semi-Furnished,Family,2 Covered,Immediately,1700 sqft,15 out of 79,East,Lodha World View,4.0,1,Garden/Park,Freehold,600 sqft,100 X 70 ft Sqft,Same Premise
3,"4 BHK Flat for Rent in Lodha Kiara, Worli, Mu...",₹3 Lac,Semi-Furnished,Bachelors/Family,3 Covered,Immediately,1676 sqft,39 out of 72,North,Lodha Kiara,4.0,1,Garden/Park,Freehold,600 sqft,100 X 70 ft Sqft,Same Premise
4,"3 BHK Flat for Rent in Bhakti Park, Wadala Ea...","₹80,000",Unfurnished,Bachelors/Family,1 Covered,Immediately,927 sqft,13 out of 18,West,Bhakti Park,3.0,1,"Garden/Park, Pool, Main Road",Freehold,600 sqft,100 X 70 ft Sqft,Same Premise

In [11]:
df['price'].unique()

array(['₹3.5 Lac', '₹41,000', '₹3.9 Lac', '₹3 Lac', '₹80,000', '₹50,000',
       '₹1.2 Lac', '₹1.1 Lac', '₹85,000', '₹2.7 Lac', '₹1.5 Lac',
       '₹1.4 Lac', '₹68,000', '₹48,000', '₹38,000', '₹65,000', '₹75,000',
       '₹35,000', '₹53,000', '₹55,000', '₹84,000', '₹6.5 Lac', '₹2 Lac',
       '₹45,000', '₹3.3 Lac', '₹70,000', '₹4.3 Lac', '₹2.3 Lac',
       '₹49,500', '₹13 Lac', '₹67,000', '₹3.2 Lac', '₹1.3 Lac',
       '₹2.4 Lac', '₹95,000', '₹30,000', '₹3.1 Lac', '₹1 Lac', '₹40,000',
       '₹72,000', '₹41,699', '₹9 Lac', '₹2.5 Lac', '₹1.7 Lac', '₹28,000',
       '₹99,000', '₹76,000', '₹5.5 Lac', '₹78,000', '₹37,000', '₹64,000',
       '₹27,000', '₹32,000', '₹36,000', '₹90,000', '₹4 Lac', '₹22,000',
       '₹31,000', '₹19,000', '₹60,000', '₹42,000', '₹26,000', '₹62,500',
       '₹1.9 Lac', '₹73,000', '₹10 Lac', '₹1.6 Lac', '₹54,000',
       '₹3.8 Lac', '₹12 Lac', '₹58,000', '₹84,500', '₹62,000', '₹3.7 Lac',
       '₹57,000', '₹2.6 Lac', '₹2.8 Lac', '₹25,500', '₹51,000', '₹18,000',
       '₹52,000', '₹2.2 Lac', '₹15,000', '₹63,000', '₹71,000', '₹11 Lac',
       '₹4.5 Lac', '₹10,000', '₹20,000', '₹6.8 Lac', '₹6 Lac', '₹11,000',
       '₹38,500', '₹16,500', '₹1.8 Lac', '₹8,000', '₹7 Lac', '₹24,000',
       '₹25,990', '₹81,000', '₹5.2 Lac', '₹34,000', '₹21,000', '₹33,500',
       '₹94,000', '₹33,000', '₹4.9 Lac', '₹55,500', '₹44,500', '₹77,000',
       '₹43,000', '₹24,500', '₹5.8 Lac', '₹25,000', '₹39,000', '₹12,000',
       '₹3.6 Lac', '₹17,000', '₹70,005', '₹2.1 Lac', '₹9,000', '₹35,500',
       '₹6,500', '₹5 Lac', '₹82,000', '₹46,500', '₹29,000', '₹18,500',
       '₹13,000', '₹14,500', '₹66,000', '₹44,000', '₹56,000', '₹36,500',
       '₹99,999', '₹23,000', '₹23,500', '₹46,000', '₹93,000', '₹10.9 Lac',
       '₹14,000', '₹42,200', '₹13,500', '₹9.5 Lac', '₹39,500', '₹96,000',
       '₹6,000', '₹20,800', '₹7,000', '₹52,500', '₹40,747', '₹7,500',
       '₹59,000', '₹32,175', '₹8,500', '₹24,900', '₹47,500', '₹48,500',
       '₹10,500', '₹4,500', '₹16,000', '₹12,860', '₹9,500', '₹25,100',
       '₹83,000', '₹2.9 Lac', '₹31,507', '₹19,500', '₹15,500', '₹35,100',
       '₹87,500', '₹34,700', '₹12,500', '₹22 Lac', '₹26,500', '₹85,500',
       '₹4,000', '₹5,000', '₹14,200', '₹30 Lac', '₹43,500', '₹15 Lac',
       '₹67,500'], dtype=object)

In [12]:
def convert_lac_to_numeric(value):
    if 'Lac' in value:
        return float(value.replace('₹', '').replace(' Lac', '')) * 100000
    else:
        return value
    
    
def remove_rupee_symbol(value):
    if isinstance(value, str) and value.startswith('₹'):
        return value[1:]
    return value

def convert_to_int(value):
    if isinstance(value, str):
        value = value.replace(',', '')
        value = int(value)
    if isinstance(value, (float, int)):
        return int(value)
    return value

In [13]:
df['price'] = df['price'].apply(convert_lac_to_numeric)
df['price'] = df['price'].apply(remove_rupee_symbol)
df['price'] = df['price'].apply(convert_to_int)
pd.to_numeric(df['price'])

0       350000
1        41000
2       390000
3       300000
4        80000
         ...
1495     50000
1496     15000
1497    900000
1498      6000
1499     12000
Name: price, Length: 1500, dtype: int64

In [14]:
df['price'].unique()

array([ 350000,   41000,  390000,  300000,   80000,   50000,  120000,
        110000,   85000,  270000,  150000,  140000,   68000,   48000,
         38000,   65000,   75000,   35000,   53000,   55000,   84000,
        650000,  200000,   45000,  330000,   70000,  430000,  229999,
         49500, 1300000,   67000,  320000,  130000,  240000,   95000,
         30000,  310000,  100000,   40000,   72000,   41699,  900000,
        250000,  170000,   28000,   99000,   76000,  550000,   78000,
         37000,   64000,   27000,   32000,   36000,   90000,  400000,
         22000,   31000,   19000,   60000,   42000,   26000,   62500,
        190000,   73000, 1000000,  160000,   54000,  380000, 1200000,
         58000,   84500,   62000,  370000,   57000,  260000,  280000,
         25500,   51000,   18000,   52000,  220000,   15000,   63000,
         71000, 1100000,  450000,   10000,   20000,  680000,  600000,
         11000,   38500,   16500,  180000,    8000,  700000,   24000,
         25990,   81000,  520000,   34000,   21000,   33500,   94000,
         33000,  490000,   55500,   44500,   77000,   43000,   24500,
        580000,   25000,   39000,   12000,  360000,   17000,   70005,
        210000,    9000,   35500,    6500,  500000,   82000,   46500,
         29000,   18500,   13000,   14500,   66000,   44000,   56000,
         36500,   99999,   23000,   23500,   46000,   93000, 1090000,
         14000,   42200,   13500,  950000,   39500,   96000,    6000,
         20800,    7000,   52500,   40747,    7500,   59000,   32175,
          8500,   24900,   47500,   48500,   10500,    4500,   16000,
         12860,    9500,   25100,   83000,  290000,   31507,   19500,
         15500,   35100,   87500,   34700,   12500, 2200000,   26500,
         85500,    4000,    5000,   14200, 3000000,   43500, 1500000,
         67500])

In [33]:
df['Floor']

0       37 out of 75
1       18 out of 48
2       15 out of 79
3       39 out of 72
4       13 out of 18
            ...
1495      1 out of 2
1496      5 out of 5
1497    13 out of 15
1498      1 out of 3
1499      1 out of 1
Name: Floor, Length: 1500, dtype: object

In [35]:
df[['floor_no', 'total_floors']] = df['Floor'].str.split(' out of ', expand=True)

In [39]:
df.drop('Floor', axis = 1, inplace = True)

In [40]:
df

,title,price,Furnishing,Tenant Preferred,Car Parking,Availability,Carpet Area,facing,Society,Bathroom,Balcony,overlooking,Ownership,Super Area,Dimensions,Owner Resides,floor_no,total_floors
0,"3 BHK Flat for Rent in Lodha World One, Worli...",350000,Semi-Furnished,Bachelors/Family,2 Covered,Immediately,2198 sqft,West,Lodha World One,3.0,3,Main Road,Freehold,600 sqft,100 X 70 ft Sqft,Same Premise,37,75
1,"1 BHK Flat for Rent in Piramal Revanta, Mulun...",41000,Semi-Furnished,Family,1 Covered,Immediately,474 sqft,East,Piramal Revanta,2.0,1,"Pool, Garden/Park, Main Road",Freehold,600 sqft,100 X 70 ft Sqft,Same Premise,18,48
2,"3 BHK Flat for Rent in Lodha World View, Worl...",390000,Semi-Furnished,Family,2 Covered,Immediately,1700 sqft,East,Lodha World View,4.0,1,Garden/Park,Freehold,600 sqft,100 X 70 ft Sqft,Same Premise,15,79
3,"4 BHK Flat for Rent in Lodha Kiara, Worli, Mu...",300000,Semi-Furnished,Bachelors/Family,3 Covered,Immediately,1676 sqft,North,Lodha Kiara,4.0,1,Garden/Park,Freehold,600 sqft,100 X 70 ft Sqft,Same Premise,39,72
4,"3 BHK Flat for Rent in Bhakti Park, Wadala Ea...",80000,Unfurnished,Bachelors/Family,1 Covered,Immediately,927 sqft,West,Bhakti Park,3.0,1,"Garden/Park, Pool, Main Road",Freehold,600 sqft,100 X 70 ft Sqft,Same Premise,13,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,"1 BHK Apartment for Rent in Laram Center CHS, ...",50000,Semi-Furnished,Bachelors/Family,1 Covered,Immediately,510 sqft,East,Laram Center CHS,1.0,1,Main Road,Freehold,600 sqft,100 X 70 ft Sqft,Same Premise,1,2
1496,1 BHK Apartment for Rent in sajheevan chs Mumbai,15000,Semi-Furnished,Bachelors/Family,1 Covered,Immediately,750 sqft,East,L&T Crescent Bay,1.0,1,Main Road,Freehold,180 sqft,100 X 70 ft Sqft,Same Premise,5,5
1497,5 BHK Apartment for Rent in Khar West Mumbai,900000,Semi-Furnished,Bachelors,1 Covered,Immediately,3000 sqft,East,L&T Crescent Bay,5.0,1,"Garden/Park, Pool",Freehold,600 sqft,100 X 70 ft Sqft,Same Premise,13,15
1498,1 BHK House for Rent in Bhim Nagar Mumbai,6000,Unfurnished,Bachelors/Family,1 Covered,Immediately,350 sqft,East,L&T Crescent Bay,1.0,1,Main Road,Freehold,600 sqft,100 X 70 ft Sqft,Same Premise,1,3
1499,1 BHK House for Rent in Chembur East Mumbai,12000,Unfurnished,Bachelors/Family,1 Covered,Immediately,450 sqft,West,L&T Crescent Bay,1.0,1,Main Road,Freehold,600 sqft,100 X 70 ft Sqft,Same Premise,1,1